### ISSUE TITLE
Maturain Bug

### ISSUE THREAD

**Issue by anirul** [anirul/Darwin#4]
Discover that sometime the position of the character is switch to `-inf` and also the dt... why?
- Added some code to prevent the client from doing it (it doesn't work?).
- Need more debugging.

**Comment by mlaagerc2c** [comment]
Sounds like overflow…

**Comment by anirul** [comment]
I wonder if this does come from the dt going wild? like if you try to move to somewhere very fast then it could corrupt the position as fast? Still experimenting...

**Comment by anirul** [comment]
I hard corrected one of the error but I still have a camera issue... still working on it!

**Comment by anirul** [comment]
So... I thinks this is ok now. This was coming from the camera as I m not using any quaternion for it it sometime freak out and put Nan in the position  of the forward vector (that contaminate the whole thing after). So I just detect when this is happening and reverting the forward to a safe direction and it work.

**Comment by anirul** [comment]
This is a memory corruption somewhere...

**Comment by anirul** [comment]
This was in effect coming from the async implementation, I reverted it 'painfully' and now it seams not to be there anymore.
